name: 'upload-release-asset-action'
description: 'An Action to upload a release asset.'
author: 'KubeVela'
inputs:
  release_id:
    description: 'ID for uploading assets to the release'
    required: true
  asset_path:
    description: 'The path to the asset you want to upload'
    required: true
  asset_name:
    description: 'The name of the asset you want to upload'
    required: true
outputs:
  id:
    description: 'The ID of the asset'
  browser_download_url:
    description: 'The URL users can navigate to in order to download the uploaded asset'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'package'
  color: 'gray-dark'